apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.appName }}
  namespace: default
  labels:
    app:  {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.appReplicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  {{ .Values.appName }}
    spec:
      containers:
      - name:  {{ .Values.appName }}
        image:  "{{ .Values.appImage }}:{{ .Values.appVersion }}"
        ports:
        - containerPort:  {{ .Values.containerPort }}
        env:
        {{- range .Values.containerEnvVar}}
        - name: {{ .key }}
          value: {{ .value | quote }}
        {{- end }}

