appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 9555
containerEnvVars:
env:
- name: PORT
  value: "9555"

servicePort: 9555
