appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 7000
containerEnvVars:
env:
- name: PORT
  value: "7000"

servicePort: 7000
